version: "3.8"

services:
  app:
    container_name: node-app
    image: task-node-app:latest
    build: .
    ports:
      - "5000:5000"  # Exposing port 5000
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://root:admin@10.0.2.209:27017/mongo?authSource=admin
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
