version: '3.8'

services:
  app:
    container_name: node-app
    image: task-node-app:latest  # Replace with your actual image
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://root:admin@10.0.2.209:27017/mongo?authSource=admin
