version: '3.8'

services:
  app:
    build: .
    container_name: node-app
    ports:
      - "5000:5000"  # Change this to match your app's port
    depends_on:
      - mongodb
      - redis
    environment:
      MONGO_URI: "mongodb://mongodb:27017/mydatabase"
      REDIS_HOST: "redis"
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: always
