services:
  app:
    build: .
    container_name: task-node-app
    ports:
      - "3000:3000"
    environment:
      MONGO_HOST: mongo-db
      MONGO_PORT: 27017
      MONGO_DB_NAME: library
      REDIS_HOST: redis-server
      REDIS_PORT: 6379
    depends_on:
      - mongo-db
      - redis-server
    restart: always

  mongo-db:
    image: mongo:7.0
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db

  redis-server:
    image: redis:latest
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo-data:
