version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://root:admin@10.0.2.209:27017/mongo?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    restart: always

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    restart: always
